<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.3.0</Version>
    <PackageProjectUrl>https://github.com/pyreymo/event-horizon</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Localization\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
    <Content Include="Assets\no-binder.avfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
    <EmbeddedResource Include="Assets\gaze-marker.png" />
  </ItemGroup>
</Project>
