<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.8.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventHorizon\EventHorizon.csproj" />
    <Reference Include="FFXIVClientStructs" HintPath="$(DALAMUD_HOME)\FFXIVClientStructs.dll" Private="true" />
    <Reference Include="InteropGenerator.Runtime" HintPath="$(DALAMUD_HOME)\InteropGenerator.Runtime.dll" Private="true" />
  </ItemGroup>
</Project>
